# Deploy to Firebase Hosting (live) from master
name: Deploy to Firebase Hosting (live)

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# Minimal permissions for reading the repo
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  deploy_live:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If you build (React/Vite/etc.), add your build here, e.g.:
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 20
      # - run: npm ci
      # - run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SOTOMONTE_A57BE }}
          projectId: sotomonte-a57be
          channelId: live
